// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TestTask.Infrastructure.Data;

#nullable disable

namespace TestTask.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TestTask.Core.Entities.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Balance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("balance");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_clients");

                    b.ToTable("clients", null, t =>
                        {
                            t.HasCheckConstraint("CK_Client_Balance_Positive", "balance >= 0");
                        });
                });

            modelBuilder.Entity("TestTask.Core.Entities.FinanceTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date_time");

                    b.Property<int>("TransactionType")
                        .HasColumnType("integer")
                        .HasColumnName("transaction_type");

                    b.HasKey("Id")
                        .HasName("pk_finance_transaction");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("IX_FinanceTransaction_ClientId");

                    b.ToTable("finance_transaction", (string)null);
                });

            modelBuilder.Entity("TestTask.Core.Entities.TransactionHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("FinanceTransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("finance_transaction_id");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modification_date");

                    b.Property<decimal>("NewClientBalance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("new_client_balance");

                    b.Property<decimal>("OldClientBalance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("old_client_balance");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_transaction_history");

                    b.HasIndex("FinanceTransactionId", "Status")
                        .IsUnique()
                        .HasDatabaseName("IX_TransactionHistory_FinanceTransactionId");

                    b.ToTable("transaction_history", null, t =>
                        {
                            t.HasCheckConstraint("CK_TransactionHistory_ClientBalance_Positive", "old_client_balance >= 0");

                            t.HasCheckConstraint("CK_TransactionHistory_NewClientBalance_Positive", "new_client_balance >= 0");
                        });
                });

            modelBuilder.Entity("TestTask.Core.Entities.FinanceTransaction", b =>
                {
                    b.HasOne("TestTask.Core.Entities.Client", "Client")
                        .WithMany("FinanceTransaction")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_finance_transaction_clients_client_id");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("TestTask.Core.Entities.TransactionHistory", b =>
                {
                    b.HasOne("TestTask.Core.Entities.FinanceTransaction", "FinanceTransaction")
                        .WithMany("TransactionHistories")
                        .HasForeignKey("FinanceTransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_transaction_history_finance_transaction_finance_transaction");

                    b.Navigation("FinanceTransaction");
                });

            modelBuilder.Entity("TestTask.Core.Entities.Client", b =>
                {
                    b.Navigation("FinanceTransaction");
                });

            modelBuilder.Entity("TestTask.Core.Entities.FinanceTransaction", b =>
                {
                    b.Navigation("TransactionHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
